version: '3.8'

services:
  client_dev:
    image: node
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./client/:/app
    command: npm start

  server_dev:
    build:
      context: server
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 8080:8080
    volumes:
      - ./server/:/app
    environment:
      SPRING_PROFILES_ACTIVE: dev
    user: appuser
    command: ./gradlew --project-cache-dir /tmp/gradle-cache bootRun
    profiles:
      - server

  mongo_dev:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_dev:/data/db
      - mongodb_config_dev:/data/configdb

volumes:
  mongodb_dev:
  mongodb_config_dev:

