version: '3.8'

services:
  client:
    build:
      context: client
      dockerfile: Deploy.dockerfile
    ports:
      - 3000:3000

  server:
    build:
      context: server
      dockerfile: Deploy.dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - 8080:8080

  mongo:
    image: mongo
    ports:
      - 27017:27017
#    volumes:
#      - mongodb:/data/db
#      - mongodb_config:/data/configdb

#volumes:
#  mongodb:
#  mongodb_config:
