package com.gustavo.competitiveprogrammingapp.information.newInformation.repositories

import com.gustavo.competitiveprogrammingapp.information.newInformation.domain.UserProblemStatus
import org.springframework.data.mongodb.repository.MongoRepository
import org.springframework.data.rest.core.annotation.RepositoryRestResource

@RepositoryRestResource
interface UserProblemStatusRepository : MongoRepository<UserProblemStatus, Int>